static/js/indexCode.js

This fixes the title colour to make it more legible in the main theme.

improve styling of custom mod area

---

campaign-trail/index.html
static/js/campaign_trail.js
static/js/sea_to_sea.js

Added STSS to maintain compatibility with NCT. From testing it seems everything works as expected.

Add sea to shining sea support

---

static/mods/2025NL_BBBvan der Plas.html
static/mods/2025NL_BBBvan_der_Plas.html
static/mods/2025NL_D66Dijkgraaf.html
static/mods/2025NL_D66Kaag.html
static/mods/2025NL_Groep OmtzigtOmtzigt.html
static/mods/2025NL_Groep_OmtzigtOmtzigt.html
static/mods/2025NL_LinksOmAboutaleb.html
static/mods/2025NL_LinksOmKlaver.html
static/mods/2025NL_LinksOmTimmermans.html
static/mods/2025NL_PVVWilders.html
static/mods/2025NL_VVDRutte.html
static/mods/2025NL_VVDYeşilgöz-Zegerius.html
static/mods/MODLOADERFILE.html

It works now, I tested all candidates on a local webserver and had none of them bug out.

fixed and re-enabled 2025NL

---

static/mods/2021DE_init.html

Makes it possible to shut off the music before it starts

Enable volume button

---

static/mods/2000ROC_Lien ChanSiew Wan-chang.html

Update 2000ROC_Lien ChanSiew Wan-chang.html

---

static/js/campaign_trail.js

Renaming of this function will make a certain mod feature much easier to implement

renamed function to open Map

---

static/mods/2000ROC_Chen Shui-BianHsiu-Lien.html

Update 2000ROC_Chen Shui-BianHsiu-Lien.html

---

static/mods/2000ROC_Song Chu-yuChang Chau-Hsiung.html

Update 2000ROC_Song Chu-yuChang Chau-Hsiung.html

---

static/mods/2028_SwiftWhitmer.html
static/mods/2028_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Discord:1989Modder Additional info:

New Mod: Swift 2028

---

static/mods/1996_-_Mouths_of_the_South_TurnerJackson.html
static/mods/1996_-_Mouths_of_the_South_TurnerKerry.html
static/mods/1996_-_Mouths_of_the_South_TurnerKohl.html
static/mods/1996_-_Mouths_of_the_South_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Accurate_Feature9970 Additional info:

New Mod: Mouths of the South

---

static/mods/2024ROC_Hou You-YiBlue-White Joint Tickets.html
static/mods/2024ROC_Hou You-YiHan Kuo-yu.html
static/mods/2024ROC_Hou You-YiKo Chih-en.html
static/mods/2024ROC_Hou You-YiZhao Shao-Kang.html
static/mods/2024ROC_Ko Wen-JeWhite-Blue Joint Tickets.html
static/mods/2024ROC_Ko Wen-JeWu.html
static/mods/2024ROC_Lai Ching-teHsiao Bi-Khim.html
static/mods/2024ROC_Terry GouLai Pei-Hsia.html
static/mods/2024ROC_init.html

Added vice presidential debates and increased the number of one-on-one conclusions.

ROC 2024 update

---

2016AARedux_SchwarzeneggerCollins.html
2016AARedux_SchwarzeneggerGraham.html
2016AARedux_SchwarzeneggerHagel.html
2016AARedux_SchwarzeneggerKasich.html
2016AARedux_SchwarzeneggerPaul.html
2016AARedux_SchwarzeneggerSandoval.html
2016AARedux_init.html
2020ARNOLD_RyanButtigieg.html
2020ARNOLD_RyanCooper.html
2020ARNOLD_RyanHarris.html
2020ARNOLD_RyanKlobuchar.html
2020ARNOLD_RyanMurphy.html
2020ARNOLD_SchwarzeneggerGraham.html
2020ARNOLD_init.html

The Schwarzenegger and Ryan sides of 2020: Arnold Amendment are done, and ready to be added to CTS. The Trump side will be coming in about 3-4 weeks, and I will just do another Pull Request when the third side to this mod is finished.

2020: Arnold Amendment (Schwarzenegger/Ryan Sides)

---

static/mods/2044_Children_of_Dusk_WalkerButterfield.html
static/mods/2044_Children_of_Dusk_WalkerEisner.html
static/mods/2044_Children_of_Dusk_WalkerSanders.html
static/mods/2044_Children_of_Dusk_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Discord: new_cod_author
Username: u/butterenergy Additional info:

New Mod: Children of Dusk 2044

---

static/mods/1988RB_JacksonHollings.html
static/mods/1988RB_JacksonLeahy.html
static/mods/1988RB_JacksonLevin.html
static/mods/1988RB_JacksonPell.html
static/mods/1988RB_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .whatnamedidiuseagain
u/WhatNameDidIUseAgain Additional info: Jesse Jackson is real

New Mod: 1988: The Rainbow Trail

---

static/mods/1960_SymingtonHumphrey.html
static/mods/1960_SymingtonJackson.html
static/mods/1960_SymingtonMeyner.html
static/mods/1960_SymingtonSmathers.html
static/mods/1960_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Discord: whatnamedidiuseagain Additional info: This is the first 1960 mod in over a year and a half

New Mod: 1960 Symington

---

static/mods/1972_On_His_Own_Term_RockefellerAgnew.html
static/mods/1972_On_His_Own_Term_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: literallynelsonrockefeller, u/OkToe2051 Additional info: Simple mod I don't believe there's anything else to say about it.

New Mod: 1972 On His Own Term

---

2020ARNOLD_RyanButtigieg.html
2020ARNOLD_RyanCooper.html
2020ARNOLD_RyanHarris.html
2020ARNOLD_RyanKlobuchar.html
2020ARNOLD_RyanMurphy.html
2020ARNOLD_SchwarzeneggerGraham.html
2020ARNOLD_TrumpFlynn.html
2020ARNOLD_init.html

Adding the Trump side for the 2020: Arnold Amendment mod, and the updated codes.

2020: Arnold Amendment Update

---

static/mods/1968Elvis_PresleyConnally.html
static/mods/1968Elvis_PresleyJackson.html
static/mods/1968Elvis_PresleyKennedy.html
static/mods/1968Elvis_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Discord: gardenoflight Additional info:

New Mod: 1968Elvis

---

static/mods/1976_JacksonBriscoe.html
static/mods/1976_JacksonFord.html
static/mods/1976_JacksonHawkins.html
static/mods/1976_JacksonLong.html
static/mods/1976_JacksonStevenson_III.html
static/mods/1976_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .whatnamedidiuseagain Additional info: Scoop is Jackson

New Mod: 1976: President from Boeing

---

static/mods/2016_New_Day_KasichCruz.html
static/mods/2016_New_Day_init.html

2016 New Day Kasich Side

---

static/mods/1872TC_SewardAdams.html
static/mods/1872TC_SewardWilson.html
static/mods/1872TC_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: hall_harrington Additional info: based on this:https://www.alternatehistory.com/forum/threads/triple-calamity-what-if-the-three-most-important-men-in-the-executive-branch-died-in-one-night.544470/

New Mod: 1872: Triple Calamity

---

static/mods/1964_-_The_Eighth_Crisis_NixonFannin.html
static/mods/1964_-_The_Eighth_Crisis_NixonScranton.html
static/mods/1964_-_The_Eighth_Crisis_NixonTower.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: rmngaming5068 Additional info: Have fun! :D

New Mod: 1964 - The Eighth Crisis

---

static/mods/2008_LL_KerryEdwards.html
static/mods/2008_LL_PaulrEVOLution.html
static/mods/2008_LL_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: halliganelysium2036 Additional info: The last upload had a small error with the background for the Kerry side that was noticed right after uploading it. I am incredibly sorry for the inconvenience

New Mod: 2008 - Liberty and Liberalism

---

static/mods/2004Joementum_LiebermanDurbin.html
static/mods/2004Joementum_LiebermanGephardt.html
static/mods/2004Joementum_LiebermanLandrieu.html
static/mods/2004Joementum_LiebermanVilsack.html
static/mods/2004Joementum_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .whatnamedidiuseagain Additional info: loe jieberman

New Mod: 2004: I've Got The Joementum!

---

static/mods/88_Afton_AftonBuchanan.html
static/mods/88_Afton_AftonDole.html
static/mods/88_Afton_AftonLugar.html
static/mods/88_Afton_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Tony Gunk
Discord: tony_gunk_
Reddit: u/murkrowplays Additional info: This is a mod set in the Five Nights at Freddy's universe, so some mild dark themes are present.

New Mod: '88 Afton

---

static/mods/2278Louisiana_LiamChamberlain.html

small ending fix

---

static/mods/1960HHH_HumphreyChandler.html
static/mods/1960HHH_HumphreyKerr.html
static/mods/1960HHH_HumphreyMagnuson.html
static/mods/1960HHH_HumphreyYarborough.html
static/mods/1960HHH_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .whatnamedidiuseagain
u/WhatNameDidIUseAgain Additional info:

New Mod: 1960 Humphrey

---

static/mods/2020ARNOLD_RyanButtigieg.html
static/mods/2020ARNOLD_RyanCooper.html
static/mods/2020ARNOLD_RyanHarris.html
static/mods/2020ARNOLD_RyanKlobuchar.html
static/mods/2020ARNOLD_RyanMurphy.html
static/mods/2020ARNOLD_SchwarzeneggerGraham.html
static/mods/2020ARNOLD_TrumpCarson.html
static/mods/2020ARNOLD_TrumpFlynn.html
static/mods/2020ARNOLD_TrumpPalin.html
static/mods/2020ARNOLD_TrumpWest.html
static/mods/2020ARNOLD_init.html

Just replace the 2020: Arnold Amendment (2020ARNOLD) files already in CTS with the new ones.
Mostly changed the base scenario to be compatible with TNCT, added some songs, and added new running-mates for Trump.

2020: Arnold Amendment "Redux"

---

static/mods/2022TimRyan_RyanDems.html

lowered it by one, because a commenter said they couldnt get it despite getting up to 3

(hopefully) fixed the biden achievement

---

static/js/campaign_trail.js

Should probably get rid of undefined rows and allow for more than four candidates in the table

Attempt at dynamic historical results

---

static/mods/2024_WoodPetrowski.html
static/mods/2024_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: se.nz (on discord)
redditornot01 (on reddit) Additional info:

New Mod: 2024: Prohibition

---

static/mods/1980c_MuskieMondale.html
static/mods/1980c_MuskieNunn.html
static/mods/1980c_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .whatnamedidiuseagain Additional info: ed muskie

New Mod: 1980c

---

static/mods/2004_GephardtEdwards.html
static/mods/2004_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: discord : @callmeterra
im in the cts discord fyi
reddit: u/bcsfan6969
Additional info: sorry for using the form, i forgot how to make a pull request on the github
note that only edwards is playable
thank you <3

New Mod: 2004 Gephardt

---

static/mods/1988Gore_GoreCuomo.html
static/mods/1988Gore_GoreGlenn.html
static/mods/1988Gore_GoreMitchell.html
static/mods/1988Gore_GoreRobb.html

some slight things were done to the endings, but nothing too major. [this was done because i was fixing the broken images from NCT, and thought adjusting the endings here was a good idea :)]

1988Gore Endings

---

static/mods/2008Reed_ReedKaine.html
static/mods/2008Reed_ReedNapolitano.html
static/mods/2008Reed_ReedPatrick.html
static/mods/2008Reed_ReedRichardson.html
static/mods/2008Reed_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: jimbo Additional info: Rhode Island is the best state

New Mod: 2008 Reed

---

static/mods/2024_WisseauSestero.html
static/mods/2024_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: u/Jeekob Additional info:

New Mod: 2024 Tommy Wisseau

---

1962 Sweet Home_WallaceAlabama.html
static/mods/1962 Sweet Home_WallaceAlabama.html
static/mods/1962 Sweet Home_init.html

Sorry for the repeat, made a slight change to account for an ending I didnt know was possible. George Wallace 1962 gubernatorial, contact trifectaofsmugness on discord if theres any issues

1962 Sweet Home

---

static/mods/2012m_McCainLieberman.html
static/mods/2012m_McCainPawlenty.html
static/mods/2012m_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: .theanswerisme Additional info:

New Mod: 2012m

---

static/mods/2012_RomneyRubio.html
static/mods/2012_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: 2johls_19955 Additional info: uhhh thanks for uhhh looking at my uhhh mod

New Mod: American Nihilism

---

static/mods/1948b_WallaceAnderson.html
static/mods/1948b_WallaceBarkley.html
static/mods/1948b_WallacePepper.html
static/mods/1948b_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: jimbo Additional info: identity war is the greatest mod ever made

New Mod: 1948b

---

static/mods/2020AEN_ButtigiegRice.html
static/mods/2020AEN_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: __wastaken (discord) Additional info:

New Mod: Alfred E. Neuman 2020

---

static/mods/2012 Redux-Obama-Biden.txt
static/mods/2012 Redux-Obama-Clinton.txt
static/mods/2012 Redux-Romney-Christie.txt
static/mods/2012 Redux-Romney-Pawlenty.txt
static/mods/2012 Redux-Romney-Portman.txt
static/mods/2012 Redux-Romney-Rubio.txt
static/mods/2012 Redux-Romney-Ryan.txt
static/mods/2012 Redux_init.txt

Looking to upload my mod 2012 Redux to the CTS mod loader. Hope I’m doing this right lol

2012 Redux CTS Upload

---

static/mods/2012_Redux_ObamaBiden.html
static/mods/2012_Redux_ObamaClinton.html
static/mods/2012_Redux_RomneyChristie.html
static/mods/2012_Redux_RomneyPawlenty.html
static/mods/2012_Redux_RomneyPortman.html
static/mods/2012_Redux_RomneyRubio.html
static/mods/2012_Redux_RomneyRyan.html
static/mods/2012_Redux_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Reddit: u/MadCowBro Additional info: Jet thinks I may have submitted pull request to wrong folder so he told me to use this form. Ty!

New Mod: 2012 Redux

---

static/mods/2024 VT_init.html

-small patch, added a further reading section

Update 2024 VT_init.html

---

static/mods/2024 VT_ScottRepublican Party.html

Update 2024 VT_ScottRepublican Party.html

---

static/mods/2024 VT_DeanDemocratic Party.html

Update 2024 VT_DeanDemocratic Party.html

---

static/mods/1978TX-19_init.html

nothing much, but:
changed the global variance and state variance to 0.01 and 0.005 respectively
also changed the background a little bit

small stuff for 1978tx-19

---

static/mods/2076_StephensonRichards.html

the creator, gelid lagopus, told me of the text that spills out and makes it hard to read. i think it should not do that now

2076 overflowing text endings

---

static/mods/2076_StephensonRichards.html

hiiiiiiii sorry once again, but the creator gelid lagopus informed me of another problem with it and its pretty small which was that the impeachment ending wouldnt show up so i fixed it up and after playing it and seeing if the changes worked it works now and appears :)

2076 - impeachment ending fixed

---

static/mods/2024Exile_init.html

Opendrive no longer loads the .mp3s for some songs, so I migrated everything over to Jukehost.

Music Player & Image Fix

---

static/mods/2024Exile_init.html

Fixed a bug relating to infinite function calling that would break loading on Firefox browsers.

Fixed Firefox Infinite Loading 

---

static/mods/2024Exile_init.html
static/mods/2024_Patriot BlocHughes.html
static/mods/MODLOADERFILE.html

Added achievements and moved CYOA ending songs to Jukehost

Achievements

---

static/mods/2024Exile_init.html
static/mods/2024_Patriot BlocHughes.html

Fixed title overflow on achievement and 2 broken image links.

Fixed Achievement Title Overflow

---

static/mods/MODLOADERFILE.html

2024ARNOLD

---

static/mods/1974_North_Dakota_Senate_Lewis_GuyNPL.html
static/mods/1974_North_Dakota_Senate_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: Wah Guy Additional info:

New Mod: 1974ND

---

static/mods/2023 Mississippi_PresleyDemocrats.html

Update 2023 Mississippi_PresleyDemocrats.html

---

static/mods/2023 Mississippi_init.html

Update 2023 Mississippi_init.html

---

static/mods/1936 RF_init.html

Replaced with Updated version of the code 1

Update 1936 RF_init.html

---

static/mods/MODLOADERFILE.html

1816 Part 2

---

static/mods/2025_to_2029_HarrisWalz.html
static/mods/2025_to_2029_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: IjbolVeteran Additional info:

New Mod: Unburdened By What has Been

---

static/mods/1969_4way_ClintonBiden.html
static/mods/1969_4way_ClintonCroft.html
static/mods/1969_4way_ClintonDukakis.html
static/mods/1969_4way_ClintonGlenn.html
static/mods/1969_4way_ClintonRockefeller.html
static/mods/1969_4way_GoldwaterBush.html
static/mods/1969_4way_GoldwaterLeMay.html
static/mods/1969_4way_GoldwaterPaul.html
static/mods/1969_4way_GoldwaterReagan.html
static/mods/1969_4way_GoldwaterSmith.html
static/mods/1969_4way_NaderDeLeon.html
static/mods/1969_4way_NaderHumphrey.html
static/mods/1969_4way_NaderSanders.html
static/mods/1969_4way_NaderSeale.html
static/mods/1969_4way_NaderStalin.html
static/mods/1969_4way_WallaceObama.html
static/mods/1969_4way_WallaceRockwell.html
static/mods/1969_4way_WallaceSchlafly.html
static/mods/1969_4way_WallaceThurmond.html
static/mods/1969_4way_WallaceTrump.html
static/mods/1969_4way_init.html

Is that April Fools mod elegible for an April Fools release or something?

April Fools mod

---

static/mods/2012_-_Razistorija_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: vernadskova Additional info: Another revised version, apologies!Push it out at 12:00 EST 06/04/2025!

New Mod: Razistorija

---

static/mods/1990 NC Senate_GanttDemocrats.html

Spelling fixes and minor changes

Update 1990 NC Senate_GanttDemocrats.html

---

static/mods/2006 Tennessee Senate_Ford Jr.Democrats.html

Update 2006 Tennessee Senate_Ford Jr.Democrats.html

---

static/mods/2006 Tennessee Senate_init.html

Update 2006 Tennessee Senate_init.html

---

static/js/campaign_trail.js

Forgot to apply it into running mate desc (e.PartyText was only applied to the candidate desc)

Applied to running mate description

---

static/mods/1960STC_HumphreyChandler.html
static/mods/1960STC_HumphreyJohnson.html
static/mods/1960STC_HumphreyKennedy.html
static/mods/1960STC_HumphreyKerr.html
static/mods/1960STC_HumphreyLausche.html
static/mods/1960STC_HumphreyMagnuson.html
static/mods/1960STC_HumphreyYarborough.html
static/mods/1960STC_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: jimbo Additional info: Silver is the best Sonic the Hedgehog character

New Mod: 1960: Some Talk Change

---

static/mods/1974 Kansas Senate

The election year's name is 1974 Kansas Senate so make that the name

Create 1974 Kansas Senate

---

static/mods/2000_DoleDanforth.html
static/mods/2000_DoleKemp.html
static/mods/2000_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: discord: army2.0
reddit: u/ArmyTwoPointOh Additional info:

New Mod: 𝙱𝚘𝚋'𝚜 𝙼𝚊𝚌𝚊𝚛𝚎𝚗𝚊.

---

static/js/campaign_trail.js

Removes redundant histhex code in case 20 by taking advantage of the fallthrough in switch statements

Use fallthrough for 2016 and 2016a

---

static/mods/ROC'04 Bian._Chen Shui BianLu Hsiu-lien.html
static/mods/ROC'04 Bian._Lien ChanSong Chu-Yu.html

Slightly modified the difficulty of A-Bian and the policy orientation of Chiayi City. And fixed two bugs

ROC'04 Bian. Bug Fixed And Balance Adjusted

---

static/mods/1856_BuchananBreckinridge.html
static/mods/1856_FillmoreDonelson.html
static/mods/1856_FrémontDayton.html

Diacritics that were causing the Code 2 Trouble Gone

1856 Final Fix

---

static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_init.html
static/mods/MODLOADERFILE.html

Added files for 2016: A Lifetime of This

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

The CTS mod loader and the manual mod loader aren't really best friends, apparently

Added missing running mates for 2016 A Lifetime of This

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

This is my last pull request, I promise.

Fix issue with issue counter for 2016 A Lifetime of This

---

static/mods/MODLOADERFILE.html
static/mods/Smoke_In_The_Air_ExeonPerson.html
static/mods/Smoke_In_The_Air_init.html

A new mod has been uploaded via the API. Contact info: u/ThePearPerson Additional info: N/A

New Mod: 2028 - Smoke In The Air

---

static/js/campaign_trail.js

**This was mainly for fix1964 at the end of the file.**
The reason there's so many additions and deletions was because I linted the file first using ESLint beforehand (yes, I'm thinking of revamping some more parts of campaign_trail.js).
Of course, let me know if some of those changes unintentionally messed up some crucial parts from working.

Remove setInterval for fix1964, use observers and event listeners instead

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html

Now all ~90 cabinet picks should show up instead of ~60 at the ending sliders. I forgot to d that

Fixed issue with not all cabinet members displaying (for 2016 ALOT)

---

static/mods/2000_BushCheney.html
static/mods/2000_init.html
static/mods/MODLOADERFILE.html

A new mod has been uploaded via the API. Contact info: @theMcCain (discord) Additional info:

New Mod: 2000 Redux

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

especially regarding the cabinet sliders + some advisor feedback tweaks

More bug fixes for 2016ALOT

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

Mostly fixes to the running mate checker, the banner system and one attempt to make the dossier more dynamic

Extra fixes for 2016ALOT

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

I used a wrong variable name when adding NCT compatibility here. oops. + a cleanup of the opponent EVs function

Fixed issue with achievements not popping up on 2016ALOT

---

static/js/campaign_trail.js

This no longer breaks TTNW. The problem was that TTNW used a separate function for slide two and slide three and tried to call `quickstats` but since `quickstats` is not a global variable, it threw an error about `quickstats` not being defined. It is now defined as `window.quickstats = [/* ... */]` instead of `const quickstats = [/* ... */]` in the previous code I tried to merge. `window` is used because I don't wanna use implicit declarations.
`vpTable` also works now.
Also includes a few fixes and improvements by StrawberryMaster.

Actually Works Now

---

static/mods/1988R_ReaganNorth.html
static/mods/1988R_init.html

NEW MOD! First mod, even though it's a complete joke.

New Mod: 1988 Ronald Reagan

---

static/js/achievements.js
static/js/modLoaderCode.js

On mobile, it was quite small and hard to read - this expands it so that it's more or less the same width as the desktop one.
Also included: minor refactoring for the DSA achievement fix (which will also make it somewhat cleaner if a future mod attempts something similar) and also a fix for custom mods not immediately appearing in the mod menu when saved or overwritten.

Accessibility fixes for the achivements menu

---

static/mods/1936L_DawesLandon.html
static/mods/1936L_DawesMcNary.html
static/mods/1936L_DawesRoosevelt.html
static/mods/1936L_HullCummings.html
static/mods/1936L_HullKennedy.html
static/mods/1936L_HullTydings.html
static/mods/1936L_LongWallace.html

fixing couple of old images
(To confirm I am the original modder)

1936L routine image update

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

some minor question effects fixes, accessibility fixes, and a refactoring of the tooltip system

Minor fixes to 2016ALOT

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html

goes back to previous behavior

Fix for a 2016ALOT achievement

---

static/mods/2024_Patriot BlocHughes.html

Update to the Code 2 to include a Campaign Headquarters that tracks ending related variables.

Update 2024_Patriot BlocHughes.html

---

static/css/community.css
static/js/achievements.js
static/js/cheats.js
static/js/modLoaderCode.js

Applies to both the mod loader and the achievements menu, which fixes #497 + a minor cleanup of cheats.js. The only noteworthy addition is that the Autoplay banner has a background to make it readable in the default theme.

Adds localstorage support to View all mods checkboxes

---

static/mods/2024 - Our Revolution_SandersHarris.html

Update 1.02 to 2024 - Our Revolution
- Fixed Marvin Gaye's name (thanks Skittie)
Thanks to u/macrohistorian for all of the following fixes
- Fixed bug that accidentally rewrote Trump Jr's econ score under A42304, aka the important fix
- Fixed A24301 to affect globalism instead of econ
- Attacking Vance on abortion ban is now a social issue, not an economic issue
- Checking for the player arming Israel for border bill now checks the correct ID for full support of Israel after initially disarming them.

Update 2024 - Our Revolution_SandersHarris.html

---

static/js/campaign_trail.js

Self-explanatory. Main content area seems to be always present when the code 2 is loaded.

Better check for running_mate_id_button and candidate_id_button

---

static/mods/2024 - Our Revolution_SandersHarris.html

Added system to backfill congressional district results after election night with accurate turnout numbers due to repeated user demands

Minor update to 2024 - Our Revolution

---

static/css/community.css
static/js/modLoaderCode.js

Makes the styling align a bit more with the rest of the navigation modal.

Standardized styling for the Go button

---

static/js/campaign_trail.js

I mainly intended this for state mods where the custom background is a map of the state (I was thinking of hud's Illinois Blagojevich mod).

Allow for changing map opacity using a variable

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

Fixes for the 2016ALOT cabinet picker

---

static/js/campaign_trail.js

This fixes a 2021DE bug where answers wouldn't show up for a particular question

Coerce question property to String

---

static/js/achievements.js

as per [this report](https://www.reddit.com/r/thecampaigntrail/comments/1mz64jj/shouldnt_the_cts_be_a_bit_modified_in_regards_to/) on Reddit.

Fix to ensure DSA also appears when 2024 is favorited

---

static/js/modLoaderCode.js

refactor theme contrast function

---

static/js/campaign_trail.js

Fix PV not appearing

---

static/js/consoleCheats.js

It was working unless you pressed a button that left the question tab, in which case it would break. It should work now

Fix bug with sortanswers

---

.gitignore
campaign-trail/index.html
static/css/community.css
static/js/answerTooltip.js
static/json/answer_variables.json

Adds a tooltip that shows the variable change associated with the selected answer. Also adds a cheat button for toggling the tooltip. Deployed changes [here](https://daxog.github.io/campaigntrailshowcase/campaign-trail/).
Currently works for these mods:
- 1962 Sweet Home
- 1972 Romney
- 1983 Chicago 
- 2000 IL-01
- 2008 Lieberman

tooltip cheat to display variable change for answers

---

static/mods/2025Canada_init.html

Got a request for the banner to be a little wider relative to its height. This PR just switches out the banner for a wider one.

Replace 2025Canada banner

---

static/mods/2000_BushCheney.html
static/mods/2000_init.html

Made 2000 redux slightly more bearable to play

---

static/mods/2016 - A Lifetime of This_ClintonBiden.html
static/mods/2016 - A Lifetime of This_ClintonBooker.html
static/mods/2016 - A Lifetime of This_ClintonCastro.html
static/mods/2016 - A Lifetime of This_ClintonGarcetti.html
static/mods/2016 - A Lifetime of This_ClintonKaine.html
static/mods/2016 - A Lifetime of This_ClintonPatrick.html
static/mods/2016 - A Lifetime of This_init.html

To reflect changes in #611, which broke the question randomizer - though this is safer anyway. Also comes with some other QoL improvements for the mod

Fix broken questions on 2016ALOT

---

static/mods/1936 - March On Washington_ButlerChild.html
static/mods/1936 - March On Washington_init.html

Changed image links to better image hosting site
Fixed EVs
Other minor fixes

MOW minor fixes

---

static/mods/MODLOADERFILE.html

1800 Part 2

---

static/mods/2012 - Obamanation_ObamaBiden.html
static/mods/2012 - Obamanation_init.html

A bunch of them. It
- has Deep State addon update immediately instead of having a 1-2 question delay, and makes it mobile-compatible
- fixes an issue where Rice and Christie did not display in their paths
- fixes an issue where the 100% mode text was saying something completely different
- fixes an issue where the tooltip images were not centered
- fixes an issue where the state info text kept being cut off (or overflowed)
- fixes an issue where the bottom banner kept displaying some trippy hover effects
- fixes an issue where the bottom banner was not centered
- fixes an issue where the padding for the game over buttons was set to 0
- fixes an issue on browsers other than Firefox (Chrome/Edge/etc.) that caused the volume slider knob to be misplaced
- fixes an issue where the ad banners' …

Accessibility and bug fixes for Obamanation Deluxe

---

static/mods/2012 - Obamanation_ObamaBiden.html
static/mods/2012 - Obamanation_init.html

More stuff.
- Fixed issue where Obama would be compromised to a permanent end twice, causing other ending slides to break
- Fixed issue where Rice would appear, disappear, re-appear, and re-disappear during her path
- Fixed issue where the Credits popup would not be draggable on mobile
- Fixed issue where several dropdowns on the start screen would be unreadable

More OBN Deluxe fixes

---

static/css/community.css
static/js/achievements.js
static/mods/1968Romney_RomneyGavin.html
static/mods/1968Romney_RomneyKirk.html
static/mods/1968Romney_init.html

Also comes with a few improvements to loading the achievements menu, especially when View all mods is checked, and also a patch to 1968 Romney that prevents the music player there from loading twice + replaces a few invisible characters that made it impossible to unlock the defined mods there.

Added search bar to achievements menu
